//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChainbotRobot.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChainbotRobot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 About Products 的本地化字符串。
        /// </summary>
        public static string AboutProducts {
            get {
                return ResourceManager.GetString("AboutProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 About 的本地化字符串。
        /// </summary>
        public static string AboutText {
            get {
                return ResourceManager.GetString("AboutText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Activity log: type = {0}, msg = {1}, msgDetails = {2} 的本地化字符串。
        /// </summary>
        public static string ActivityLog {
            get {
                return ResourceManager.GetString("ActivityLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to remove the current package? 的本地化字符串。
        /// </summary>
        public static string AreYouSureToRemoveThePackage {
            get {
                return ResourceManager.GetString("AreYouSureToRemoveThePackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure you want to reset to default settings? 的本地化字符串。
        /// </summary>
        public static string AreYouSureToReset {
            get {
                return ResourceManager.GetString("AreYouSureToReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The software failed the authorization test, please register the product! 的本地化字符串。
        /// </summary>
        public static string AuthorizationTestFailed {
            get {
                return ResourceManager.GetString("AuthorizationTestFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically open the main window after startup 的本地化字符串。
        /// </summary>
        public static string AutomaticallyOpenWindowContent {
            get {
                return ResourceManager.GetString("AutomaticallyOpenWindowContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatically start at boot 的本地化字符串。
        /// </summary>
        public static string AutomaticallyStartAtBootContent {
            get {
                return ResourceManager.GetString("AutomaticallyStartAtBootContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 List of available processes 的本地化字符串。
        /// </summary>
        public static string AvailableProcessesListText {
            get {
                return ResourceManager.GetString("AvailableProcessesListText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View logs 的本地化字符串。
        /// </summary>
        public static string BrowseLogsToolTip {
            get {
                return ResourceManager.GetString("BrowseLogsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Extensions 的本地化字符串。
        /// </summary>
        public static string BrowserExtensionsToolTip {
            get {
                return ResourceManager.GetString("BrowserExtensionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browser Extensions 的本地化字符串。
        /// </summary>
        public static string BrowserWindowTitle {
            get {
                return ResourceManager.GetString("BrowserWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Browse videos 的本地化字符串。
        /// </summary>
        public static string BrowseVideos {
            get {
                return ResourceManager.GetString("BrowseVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string CancelContent {
            get {
                return ResourceManager.GetString("CancelContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Chainbot Executor does not exist! Please check whether it is deleted by antivirus software by mistake 的本地化字符串。
        /// </summary>
        public static string CannotFindChainbotExecutor {
            get {
                return ResourceManager.GetString("CannotFindChainbotExecutor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Master file not found! 的本地化字符串。
        /// </summary>
        public static string CannotFindMainXamlFileError {
            get {
                return ResourceManager.GetString("CannotFindMainXamlFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unable to find project configuration file project.json. 的本地化字符串。
        /// </summary>
        public static string CannotFindProjectJsonFile {
            get {
                return ResourceManager.GetString("CannotFindProjectJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] ChainbotRobotSettings {
            get {
                object obj = ResourceManager.GetObject("ChainbotRobotSettings", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Chainbot Robot 的本地化字符串。
        /// </summary>
        public static string ChainbotRobotTitle {
            get {
                return ResourceManager.GetString("ChainbotRobotTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string CloseContent {
            get {
                return ResourceManager.GetString("CloseContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Machine Id: 的本地化字符串。
        /// </summary>
        public static string ComputerId {
            get {
                return ResourceManager.GetString("ComputerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Computer Name: 的本地化字符串。
        /// </summary>
        public static string ComputerName {
            get {
                return ResourceManager.GetString("ComputerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirm 的本地化字符串。
        /// </summary>
        public static string ConfirmText {
            get {
                return ResourceManager.GetString("ConfirmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Center: 的本地化字符串。
        /// </summary>
        public static string ControlCenterAddress {
            get {
                return ResourceManager.GetString("ControlCenterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Control Center Configuration 的本地化字符串。
        /// </summary>
        public static string ControlCenterConfiguration {
            get {
                return ResourceManager.GetString("ControlCenterConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy information 的本地化字符串。
        /// </summary>
        public static string CopyInformation {
            get {
                return ResourceManager.GetString("CopyInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable Control Center 的本地化字符串。
        /// </summary>
        public static string EnableControlCenter {
            get {
                return ResourceManager.GetString("EnableControlCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Enable screen recording 的本地化字符串。
        /// </summary>
        public static string EnableScreenRecording {
            get {
                return ResourceManager.GetString("EnableScreenRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End of process run 的本地化字符串。
        /// </summary>
        public static string EndProcessRun {
            get {
                return ResourceManager.GetString("EndProcessRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Screen recording ends 的本地化字符串。
        /// </summary>
        public static string EndScreenRecording {
            get {
                return ResourceManager.GetString("EndScreenRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export the machine code file 的本地化字符串。
        /// </summary>
        public static string ExportMachineCodeContent {
            get {
                return ResourceManager.GetString("ExportMachineCodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please export the machine code file and send it to the authorized party to complete the authorization 的本地化字符串。
        /// </summary>
        public static string ExportMachineCodeToolTip {
            get {
                return ResourceManager.GetString("ExportMachineCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Frames: 的本地化字符串。
        /// </summary>
        public static string FramesText {
            get {
                return ResourceManager.GetString("FramesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import authorization code file 的本地化字符串。
        /// </summary>
        public static string ImportMachineCodeContent {
            get {
                return ResourceManager.GetString("ImportMachineCodeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Select the authorization code file to complete the import, or directly drag the authorization code file to the current window 的本地化字符串。
        /// </summary>
        public static string ImportMachineCodeToolTip {
            get {
                return ResourceManager.GetString("ImportMachineCodeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP Address: 的本地化字符串。
        /// </summary>
        public static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Loading project dependencies 的本地化字符串。
        /// </summary>
        public static string LoadingProjectDependencies {
            get {
                return ResourceManager.GetString("LoadingProjectDependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error loading project dependencies! 的本地化字符串。
        /// </summary>
        public static string LoadingProjectDependenciesError {
            get {
                return ResourceManager.GetString("LoadingProjectDependenciesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Locate the current package 的本地化字符串。
        /// </summary>
        public static string LocateCurrentPackage {
            get {
                return ResourceManager.GetString("LocateCurrentPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program is not registered 的本地化字符串。
        /// </summary>
        public static string NotRegisteredText {
            get {
                return ResourceManager.GetString("NotRegisteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string OKContent {
            get {
                return ResourceManager.GetString("OKContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Name: {0}\r\nVersion: {1}\r\nRelease Notes: {2}\r\nProject Description: {3}\r\nRelease Time: {4} 的本地化字符串。
        /// </summary>
        public static string PackageToolTip {
            get {
                return ResourceManager.GetString("PackageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permanent 的本地化字符串。
        /// </summary>
        public static string PermanentText {
            get {
                return ResourceManager.GetString("PermanentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Process start 的本地化字符串。
        /// </summary>
        public static string ProcessStart {
            get {
                return ResourceManager.GetString("ProcessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 An exception occurred during the process running! 的本地化字符串。
        /// </summary>
        public static string ProjectStartError {
            get {
                return ResourceManager.GetString("ProjectStartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Prompt 的本地化字符串。
        /// </summary>
        public static string PromptText {
            get {
                return ResourceManager.GetString("PromptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quality: 的本地化字符串。
        /// </summary>
        public static string QualityText {
            get {
                return ResourceManager.GetString("QualityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Retention days: 的本地化字符串。
        /// </summary>
        public static string RecordingLimitDays {
            get {
                return ResourceManager.GetString("RecordingLimitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recording settings 的本地化字符串。
        /// </summary>
        public static string RecordingSettings {
            get {
                return ResourceManager.GetString("RecordingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Refresh 的本地化字符串。
        /// </summary>
        public static string RefreshToolTip {
            get {
                return ResourceManager.GetString("RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Program is registered 的本地化字符串。
        /// </summary>
        public static string RegisteredText {
            get {
                return ResourceManager.GetString("RegisteredText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Register your product 的本地化字符串。
        /// </summary>
        public static string RegisterYourProduct {
            get {
                return ResourceManager.GetString("RegisterYourProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration Information 的本地化字符串。
        /// </summary>
        public static string RegistrationInformationHeader {
            get {
                return ResourceManager.GetString("RegistrationInformationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove the current package 的本地化字符串。
        /// </summary>
        public static string RemoveCurrentPackage {
            get {
                return ResourceManager.GetString("RemoveCurrentPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Reset 的本地化字符串。
        /// </summary>
        public static string ResetSettingsContent {
            get {
                return ResourceManager.GetString("ResetSettingsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Running 的本地化字符串。
        /// </summary>
        public static string RunningText {
            get {
                return ResourceManager.GetString("RunningText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The screen recording begins ... 的本地化字符串。
        /// </summary>
        public static string ScreenRecordingStarted {
            get {
                return ResourceManager.GetString("ScreenRecordingStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search 的本地化字符串。
        /// </summary>
        public static string SearchHintText {
            get {
                return ResourceManager.GetString("SearchHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Search results are empty 的本地化字符串。
        /// </summary>
        public static string SearchResultEmptyText {
            get {
                return ResourceManager.GetString("SearchResultEmptyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string StartText {
            get {
                return ResourceManager.GetString("StartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Status : 的本地化字符串。
        /// </summary>
        public static string StatusText {
            get {
                return ResourceManager.GetString("StatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System settings 的本地化字符串。
        /// </summary>
        public static string SystemSettingsHeader {
            get {
                return ResourceManager.GetString("SystemSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The process starts ... 的本地化字符串。
        /// </summary>
        public static string TheProcessStarted {
            get {
                return ResourceManager.GetString("TheProcessStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 till 的本地化字符串。
        /// </summary>
        public static string TillText {
            get {
                return ResourceManager.GetString("TillText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update 的本地化字符串。
        /// </summary>
        public static string UpdateText {
            get {
                return ResourceManager.GetString("UpdateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User settings 的本地化字符串。
        /// </summary>
        public static string UserSettings {
            get {
                return ResourceManager.GetString("UserSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validity period: 的本地化字符串。
        /// </summary>
        public static string ValidityPeriodText {
            get {
                return ResourceManager.GetString("ValidityPeriodText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Version: 的本地化字符串。
        /// </summary>
        public static string VersionText {
            get {
                return ResourceManager.GetString("VersionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A workflow is already running, please wait for it to finish before running! 的本地化字符串。
        /// </summary>
        public static string WorkflowAlreadyRunning {
            get {
                return ResourceManager.GetString("WorkflowAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 yyyyMMddHHmmss 的本地化字符串。
        /// </summary>
        public static string YYYYMMDD {
            get {
                return ResourceManager.GetString("YYYYMMDD", resourceCulture);
            }
        }
    }
}
