//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Plugins.Shared.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Plugins.Shared.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 (Collection) 的本地化字符串。
        /// </summary>
        public static string Arguments {
            get {
                return ResourceManager.GetString("Arguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Common 的本地化字符串。
        /// </summary>
        public static string Category1 {
            get {
                return ResourceManager.GetString("Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 C#.Net Code 的本地化字符串。
        /// </summary>
        public static string CodeEditorCSharpLabel {
            get {
                return ResourceManager.GetString("CodeEditorCSharpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Editor 的本地化字符串。
        /// </summary>
        public static string CodeEditorDialogTitle {
            get {
                return ResourceManager.GetString("CodeEditorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VB.Net Code 的本地化字符串。
        /// </summary>
        public static string CodeEditorVBLabel {
            get {
                return ResourceManager.GetString("CodeEditorVBLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CSharp_Mode {
            get {
                object obj = ResourceManager.GetObject("CSharp_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] CSharp_Mode_Light {
            get {
                object obj = ResourceManager.GetObject("CSharp_Mode_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] cursor {
            get {
                object obj = ResourceManager.GetObject("cursor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Specifies to continue executing the remaining activities even if the current activity failed. Only boolean values (True, False) are supported. 的本地化字符串。
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ContinueOnError 的本地化字符串。
        /// </summary>
        public static string DisplayName1 {
            get {
                return ResourceManager.GetString("DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DubleClick To View 的本地化字符串。
        /// </summary>
        public static string DubleClickToViewText {
            get {
                return ResourceManager.GetString("DubleClickToViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Coordinate 的本地化字符串。
        /// </summary>
        public static string HintWindow_Coordinate {
            get {
                return ResourceManager.GetString("HintWindow_Coordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ESC] or RMB 的本地化字符串。
        /// </summary>
        public static string HintWindow_Esc {
            get {
                return ResourceManager.GetString("HintWindow_Esc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似     Exit 的本地化字符串。
        /// </summary>
        public static string HintWindow_EscDescription {
            get {
                return ResourceManager.GetString("HintWindow_EscDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [F2] or MMB 的本地化字符串。
        /// </summary>
        public static string HintWindow_F2 {
            get {
                return ResourceManager.GetString("HintWindow_F2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似      Delay 的本地化字符串。
        /// </summary>
        public static string HintWindow_F2Description {
            get {
                return ResourceManager.GetString("HintWindow_F2Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hotkey: 的本地化字符串。
        /// </summary>
        public static string HintWindow_Hotkey {
            get {
                return ResourceManager.GetString("HintWindow_Hotkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似                     Switch to UIA 的本地化字符串。
        /// </summary>
        public static string HintWindow_UIADescription {
            get {
                return ResourceManager.GetString("HintWindow_UIADescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] JavaScript_Mode {
            get {
                object obj = ResourceManager.GetObject("JavaScript_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] JavaScript_Mode_Light {
            get {
                object obj = ResourceManager.GetObject("JavaScript_Mode_Light", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 JavaScript Script 的本地化字符串。
        /// </summary>
        public static string JavaScriptEditorLabel {
            get {
                return ResourceManager.GetString("JavaScriptEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] Python_Mode {
            get {
                object obj = ResourceManager.GetObject("Python_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Python Script 的本地化字符串。
        /// </summary>
        public static string PythonScriptEditorLabel {
            get {
                return ResourceManager.GetString("PythonScriptEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Script Editor 的本地化字符串。
        /// </summary>
        public static string ScriptEditorDialogTitle {
            get {
                return ResourceManager.GetString("ScriptEditorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector Content 的本地化字符串。
        /// </summary>
        public static string Selector {
            get {
                return ResourceManager.GetString("Selector", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Selector Editor 的本地化字符串。
        /// </summary>
        public static string SelectorEditorDialogTitle {
            get {
                return ResourceManager.GetString("SelectorEditorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Highlight 的本地化字符串。
        /// </summary>
        public static string SelectorEditorHighlightButton {
            get {
                return ResourceManager.GetString("SelectorEditorHighlightButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Text Editor 的本地化字符串。
        /// </summary>
        public static string TextEditorDialogTitle {
            get {
                return ResourceManager.GetString("TextEditorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VBA Script 的本地化字符串。
        /// </summary>
        public static string VBAScriptEditorLabel {
            get {
                return ResourceManager.GetString("VBAScriptEditorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        public static byte[] VBNET_Mode {
            get {
                object obj = ResourceManager.GetObject("VBNET_Mode", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
